apiVersion: apps/v1
kind: Deployment
metadata:
  name: botflow-viewer-app
  annotations:
    secret.reloader.stakater.com/reload: "botflow-viewer-secrets"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: botflow-viewer-app
  template:
    metadata:
      labels:
        app: botflow-viewer-app
        department: backend
        environment: PROD
    spec:
      containers:
      - name: botflow-viewer-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: botflow-viewer-secrets
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: "X-Forwarded-Host"
              value: "botflow-viewer.tec.pet"
          initialDelaySeconds: 240
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: "X-Forwarded-Host"
              value: "botflow-viewer.tec.pet"
          initialDelaySeconds: 240
          periodSeconds: 15
        resources:
          requests:
            cpu: "2000m"
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"botflow-viewer-backendconfig"}}'
  name: botflow-viewer-service
spec:
  type: ClusterIP
  selector:
    app: botflow-viewer-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
