apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: botflow-viewer-scheduled-scaler
  namespace: tecpet-dev-app
spec:
  scaleTargetRef:
    name: botflow-viewer-app
  minReplicaCount: 0
  maxReplicaCount: 3
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: America/Sao_Paulo
        start: 0 8 * * 1-5
        end: 0 20 * * 1-5
        desiredReplicas: "1"
