apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botflow-viewer-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: botflow-viewer-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: botflow-viewer-dev-secrets
